const divElement = document.createElement('div');
document.body.appendChild(divElement);
divElement.classList.add('background-div');
const heading = document.createElement('h1');
heading.innerText = 'Welcome to the Book';
heading.style.color = '#333';
heading.style.textAlign = 'center';
divElement.appendChild(heading);
const paragraph = document.createElement('p');
paragraph.innerText = 'Nothing is impossible, the word itself says "I\'m possible!"';
paragraph.style.color = '#555';
paragraph.style.textAlign = 'center';
divElement.appendChild(paragraph);
const readBookHeading = document.createElement('h4');
readBookHeading.innerText = 'Read Book';
readBookHeading.style.color = '#333';
readBookHeading.style.textAlign = 'center';
divElement.appendChild(readBookHeading);
const largeTextParagraph = document.createElement('p');
largeTextParagraph.innerText = 'This is some large text describing the book in detail. It might be a summary or an introduction.';
largeTextParagraph.style.color = '#333';
largeTextParagraph.style.textAlign = 'center';
divElement.appendChild(largeTextParagraph);
const button = document.createElement('button');
button.innerText = 'Start Reading';
button.style.color = '#fff';
button.style.backgroundColor = '#4CAF50';
button.style.border = 'none';
button.style.borderRadius = '5px';
button.style.padding = '10px 20px';
button.style.cursor = 'pointer';
const buttonContainer = document.createElement('div');
buttonContainer.classList.add('button-container');
buttonContainer.appendChild(button);
divElement.appendChild(buttonContainer);
const skipIntroParagraph = document.createElement('p');
skipIntroParagraph.innerText = 'Skip Introduction';
skipIntroParagraph.style.color = '#555';
skipIntroParagraph.style.textDecoration = 'underline';
skipIntroParagraph.style.textAlign = 'center';
divElement.appendChild(skipIntroParagraph);
